name: Run Cypress Tests

on:
  push:
    branches:
      - petProject
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Cypress Run
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: QA_JobApplication_Automation
